[package]
name = "wizify_derive"
version = "0.1.0"
edition = "2024"

[lib]
name = "wizify_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "*"
syn = { version = "*", features = ["extra-traits"]}
quote = "*"
proc-macro-error2 = "*"
